### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by Byggvir** [wlanslovenija/tunneldigger#125]
Got following error when starting tunneldigger
```
root@voreifel1:/etc/tunneldigger# /srv/tunneldigger/env_tunneldigger/bin/python -m tunneldigger_broker.main /etc/tunneldigger/hood-rheinbach.cfg
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/srv/tunneldigger/env_tunneldigger/lib/python2.7/site-packages/tunneldigger_broker-0.3.0-py2.7-linux-x86_64.egg/tunneldigger_broker/main.py", line 1, in <module>
    import configparser
ImportError: No module named configparser
```

**Comment by RalfJung** [comment]
Looks like you are using Python 2? Tunneldigger requires Python 3.

**Comment by Byggvir** [comment]
Yes. Found out that my installation was a little outdated. Changed to python3 now.
