### ISSUE TITLE
broker throwing OSError on creation of timers

### ISSUE THREAD

**Issue by pmelange** [wlanslovenija/tunneldigger#170]
I have the broker running on OpenWrt and am seeing the following in the log file:

```
Sat Jul 29 16:06:10 2023 daemon.err python[32619]: [ERROR/tunneldigger.broker] Unhandled exception while creating tunnel 100:
Sat Jul 29 16:06:10 2023 daemon.err python[32619]: [ERROR/tunneldigger.broker] Traceback (most recent call last):
Sat Jul 29 16:06:10 2023 daemon.err python[32619]:   File "/usr/lib/python3.11/site-packages/tunneldigger_broker/broker.py", line 144, in create_tunnel
Sat Jul 29 16:06:10 2023 daemon.err python[32619]:     tunnel.setup_tunnel()
Sat Jul 29 16:06:10 2023 daemon.err python[32619]:   File "/usr/lib/python3.11/site-packages/tunneldigger_broker/tunnel.py", line 138, in setup_tunnel
Sat Jul 29 16:06:10 2023 daemon.err python[32619]:     self.create_timer(self.keepalive, timeout=random.randrange(3, 15), interval=5)
Sat Jul 29 16:06:10 2023 daemon.err python[32619]:   File "/usr/lib/python3.11/site-packages/tunneldigger_broker/network.py", line 85, in create_timer
Sat Jul 29 16:06:10 2023 daemon.err python[32619]:     timerfd.settime(timer, 0, timerfd.itimerspec(value=timeout, interval=interval))
Sat Jul 29 16:06:10 2023 daemon.err python[32619]:   File "/usr/lib/python3.11/site-packages/tunneldigger_broker/timerfd.py", line 124, in settime
Sat Jul 29 16:06:10 2023 daemon.err python[32619]:     ret = libc.timerfd_settime(ufd, flags, ctypes.pointer(new_value), ctypes.pointer(old_value))
Sat Jul 29 16:06:10 2023 daemon.err python[32619]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sat Jul 29 16:06:10 2023 daemon.err python[32619]:   File "/usr/lib/python3.11/site-packages/tunneldigger_broker/timerfd.py", line 103, in errcheck
Sat Jul 29 16:06:10 2023 daemon.err python[32619]:     raise OSError(errno, os.strerror(errno))
Sat Jul 29 16:06:10 2023 daemon.err python[32619]: OSError: [Errno 22] Invalid argument
Sat Jul 29 16:06:10 2023 daemon.err python[32619]:
Sat Jul 29 16:06:10 2023 daemon.err python[32619]: [WARNING/tunneldigger.protocol] Failed to create tunnel (b6:86:a3:a9:cd:b3:fa:8e:07:c9) while processing prepare request.
```

and with strace I see this
```
timerfd_settime64(9, 0, {it_interval={tv_sec=21474836480, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=18446744072498689248}}, 0xb7288d28) = -1 EINVAL (Invalid argument) 
```

any help getting this working would be appreciated.

**Comment by pmelange** [comment]
sorry for the noise.  I tried it on a different architecture  and I don't get these errors.

Old setup : WDR4900
New setup: RB 750GR3
